name: Go CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-test:
    name: Lint, Nilaway, Build & Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.56.2

    - name: Run golangci-lint
      run: golangci-lint run ./...

    - name: Install nilaway
      run: |
        go install github.com/google/nilaway/cmd/nilaway@latest

    - name: Run nilaway
      run: nilaway ./...

    - name: Build
      run: go build -v ./...

    - name: Run Tests
      run: go test -v ./...
